# Generated by Django 2.2.4 on 2019-10-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191029_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blend',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
