# Generated by Django 2.2.4 on 2019-10-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191029_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
